cd /testbed/TobikoData/sqlmesh
git reset --hard cd0557b1656c3733fa340e1651064be8c96e48ee
conda create -n testbed -y python=3.9
conda run -n activate testbed python -m venv /.venv/sqlmesh/posix_3.9_sqlglot.rs.27.6.0
/.venv/sqlmesh/posix_3.9_sqlglot.rs.27.6.0/bin/python -m pip install --upgrade pip
/.venv/sqlmesh/posix_3.9_sqlglot.rs.27.6.0/bin/python -m pip install -e .
pip install pytest pytest-json-report toml debugpy pytest_mock pytest-xdist
pip install "agate==1.7.1"
pip install "beautifulsoup4"
pip install "clickhouse-connect"
pip install "cryptography"
pip install "databricks-sql-connector"
pip install "dbt-bigquery"
pip install "dbt-core"
pip install "dbt-duckdb>=1.7.1"
pip install "dbt-snowflake"
pip install "dbt-athena-community"
pip install "dbt-clickhouse"
pip install "dbt-databricks"
pip install "dbt-redshift"
pip install "dbt-trino"
pip install "Faker"
pip install "google-auth"
pip install "google-cloud-bigquery"
pip install "google-cloud-bigquery-storage"
pip install "httpx"
pip install "mypy~=1.13.0"
pip install "pandas-stubs"
pip install "pre-commit"
pip install "psycopg2-binary"
pip install "pydantic"
pip install "PyAthena[Pandas]"
pip install "PyGithub>=2.6.0"
pip install "pyodbc>=5.0.0"
pip install "pyperf"
pip install "pyspark~=3.5.0"
pip install "pytest"
pip install "pytest-asyncio"
pip install "pytest-mock"
pip install "pytest-retry"
pip install "pytest-xdist"
pip install "pytz"
pip install "redshift_connector"
pip install "ruff~=0.11.0"
pip install "snowflake-connector-python[pandas,secure-local-storage]>=3.0.2"
pip install "sqlalchemy-stubs"
pip install "trino"
pip install "types-croniter"
pip install "types-dateparser"
pip install "types-PyMySQL"
pip install "types-python-dateutil"
pip install "types-pytz"
pip install "types-requests==2.28.8"
pip install "typing-extensions"
pip install "sqlglot[rs]~=27.6.0"