python -m pip install --upgrade pip
cd data/repo/CTFd/CTFd
python -m pip install --no-deps "alembic==1.16.4"
python -m pip install --no-deps "aniso8601==10.0.1"
python -m pip install --no-deps "attrs==25.3.0"
python -m pip install --no-deps "babel==2.17.0"
python -m pip install --no-deps "banal==1.0.6"
python -m pip install --no-deps "bcrypt==4.0.1"
python -m pip install --no-deps "boto3==1.35.27"
python -m pip install --no-deps "botocore==1.35.99"
python -m pip install --no-deps "cachelib==0.9.0"
python -m pip install --no-deps "certifi==2025.8.3"
python -m pip install --no-deps "cffi==1.17.1"
python -m pip install --no-deps "charset-normalizer==3.4.3"
python -m pip install --no-deps "click==8.2.1"
python -m pip install --no-deps "cmarkgfm==2024.11.20"
python -m pip install --no-deps "cryptography==45.0.6"
python -m pip install --no-deps "dataset==1.6.2"
python -m pip install --no-deps "flask==2.1.3"
python -m pip install --no-deps "flask-babel==2.0.0"
python -m pip install --no-deps "flask-caching==2.3.1"
python -m pip install --no-deps "flask-marshmallow==0.10.1"
python -m pip install --no-deps "flask-migrate==2.5.3"
python -m pip install --no-deps "flask-restx==1.3.0"
python -m pip install --no-deps "flask-script==2.0.6"
python -m pip install --no-deps "flask-sqlalchemy==2.5.1"
python -m pip install --no-deps "freezegun==1.5.5"
python -m pip install --no-deps "gevent==25.5.1"
python -m pip install --no-deps "greenlet==3.2.4"
python -m pip install --no-deps "gunicorn==23.0.0"
python -m pip install --no-deps "idna==3.10"
python -m pip install --no-deps "importlib-resources==6.5.2"
python -m pip install --no-deps "itsdangerous==2.2.0"
python -m pip install --no-deps "jinja2==3.1.6"
python -m pip install --no-deps "jmespath==1.0.1"
python -m pip install --no-deps "jsonschema==4.25.0"
python -m pip install --no-deps "jsonschema-specifications==2025.4.1"
python -m pip install --no-deps "mako==1.3.10"
python -m pip install --no-deps "markupsafe==3.0.2"
python -m pip install --no-deps "marshmallow==2.20.2"
python -m pip install --no-deps "marshmallow-sqlalchemy==0.17.0"
python -m pip install --no-deps "maxminddb==1.5.4"
python -m pip install --no-deps "nh3==0.3.0"
python -m pip install --no-deps "packaging==25.0"
python -m pip install --no-deps "passlib==1.7.4"
python -m pip install --no-deps "pillow==11.3.0"
python -m pip install --no-deps "pycparser==2.22"
python -m pip install --no-deps "pydantic==1.6.2"
python -m pip install --no-deps "pymysql[rsa]==1.1.1"
python -m pip install --no-deps "python-dateutil==2.9.0.post0"
python -m pip install --no-deps "python-dotenv==0.13.0"
python -m pip install --no-deps "python-geoacumen-city==2023.4.15"
python -m pip install --no-deps "pytz==2025.2"
python -m pip install --no-deps "redis==4.5.5"
python -m pip install --no-deps "referencing==0.36.2"
python -m pip install --no-deps "requests==2.32.4"
python -m pip install --no-deps "rpds-py==0.27.0"
python -m pip install --no-deps "s3transfer==0.10.4"
python -m pip install --no-deps "six==1.17.0"
python -m pip install --no-deps "sqlalchemy==1.4.54"
python -m pip install --no-deps "sqlalchemy-utils==0.41.1"
python -m pip install --no-deps "tenacity==9.1.2"
python -m pip install --no-deps "typing-extensions==4.14.1"
python -m pip install --no-deps "urllib3==2.5.0"
python -m pip install --no-deps "werkzeug==2.2.3"
python -m pip install --no-deps "wtforms==2.3.1"
python -m pip install --no-deps "zope-event==5.1.1"
python -m pip install --no-deps "zope-interface==7.2"
python -m pip install --no-deps "pip-tools==5.4.0"
python -m pip install --no-deps "pytest==8.4.2"
python -m pip install --no-deps "pytest-randomly==4.0.1"
python -m pip install --no-deps "coverage==7.10.7"
python -m pip install --no-deps "psycopg2-binary==2.9.6"
python -m pip install --no-deps "moto==4.1.11"
python -m pip install --no-deps "bandit==1.8.6"
python -m pip install --no-deps "flask_profiler==1.8.1"
python -m pip install "pytest-xdist==3.8.0"
python -m pip install --no-deps "pytest-cov==7.0.0"
python -m pip install --no-deps "sphinx_rtd_theme==0.4.3"
python -m pip install --no-deps "flask-debugtoolbar==0.11.0"
python -m pip install "Faker==4.1.0"
python -m pip install --no-deps "pipdeptree==2.2.0"
python -m pip install "pytest-sugar==1.1.1"
python -m pip install pybluemonday
python -m pip install 'flask==2.1.3'
python -m pip install 'werkzeug==2.2.3'
python -m pip install pytest pytest-json-report toml