python -m pip install --upgrade pip
cd data/repo/CTFd/CTFd
python -m pip install alembic==1.4.3
python -m pip install aniso8601==8.0.0
python -m pip install attrs==20.3.0
python -m pip install bcrypt==3.1.7
python -m pip install boto3==1.13.9
python -m pip install botocore==1.16.26
python -m pip install certifi==2020.11.8
python -m pip install cffi==1.14.3
python -m pip install chardet==3.0.4
python -m pip install click==7.1.2
python -m pip install cmarkgfm==0.4.2
python -m pip install dataset==1.3.1
python -m pip install docutils==0.15.2
python -m pip install flask-caching==1.8.0
python -m pip install flask-marshmallow==0.10.1
python -m pip install flask-migrate==2.5.3
python -m pip install flask-restx==0.2.0
python -m pip install flask-script==2.0.6
python -m pip install flask-sqlalchemy==2.4.3
python -m pip install flask==1.1.2
python -m pip install gevent==20.9.0
python -m pip install greenlet==0.4.17
python -m pip install gunicorn==20.0.4
python -m pip install idna==2.10
python -m pip install importlib-metadata==3.7.3
python -m pip install itsdangerous==1.1.0
python -m pip install jinja2==2.11.3
python -m pip install jmespath==0.10.0
python -m pip install jsonschema==3.2.0
python -m pip install mako==1.1.3
python -m pip install markupsafe==1.1.1
python -m pip install marshmallow-sqlalchemy==0.17.0
python -m pip install marshmallow==2.20.2
python -m pip install maxminddb==1.5.4
python -m pip install passlib==1.7.2
python -m pip install pybluemonday==0.0.7
python -m pip install pycparser==2.20
python -m pip install pydantic==1.6.2
python -m pip install pymysql==0.9.3
python -m pip install pyrsistent==0.17.3
python -m pip install python-dateutil==2.8.1
python -m pip install python-dotenv==0.13.0
python -m pip install python-editor==1.0.4
python -m pip install python-geoacumen-city==0.0.1
python -m pip install pytz==2020.4
python -m pip install redis==3.5.2
python -m pip install requests==2.23.0
python -m pip install s3transfer==0.3.3
python -m pip install six==1.15.0
python -m pip install sqlalchemy-utils==0.36.6
python -m pip install sqlalchemy==1.3.17
python -m pip install tenacity==6.2.0
python -m pip install typing-extensions==3.7.4.3
python -m pip install urllib3==1.25.11
python -m pip install werkzeug==1.0.1
python -m pip install wtforms==2.3.1
python -m pip install zipp==3.4.1
python -m pip install zope.event==4.5.0
python -m pip install zope.interface==5.2.0
python -m pip install pip-tools==5.4.0
python -m pip install pytest==5.4.2
python -m pip install pytest-randomly==3.4.0
python -m pip install coverage==5.1
python -m pip install flake8==3.8.2
python -m pip install freezegun==0.3.15
python -m pip install psycopg2-binary==2.8.6
python -m pip install codecov==2.1.7
python -m pip install moto==1.3.16
python -m pip install bandit==1.6.2
python -m pip install flask_profiler==1.8.1
python -m pip install pytest-xdist==1.32.0
python -m pip install pytest-cov==2.9.0
python -m pip install sphinx_rtd_theme==0.4.3
python -m pip install flask-debugtoolbar==0.11.0
python -m pip install isort==4.3.21
python -m pip install flake8-isort==3.0.0
python -m pip install Faker==4.1.0
python -m pip install pipdeptree==0.13.2
python -m pip install black==19.10b0
python -m pip install pytest-sugar==0.9.4
python -m pip install flake8-comprehensions==3.3.1
python -m pip install flake8-bugbear==20.11.1
python -m pip install jinja2==2.11.3
python -m pip install markupsafe==1.1.1
python -m pip install pybluemonday
python -m pip install gevent
python -m pip install pytest pytest-json-report toml