
# 基础镜像：Ubuntu 22.04
FROM ubuntu:22.04

LABEL org.opencontainers.image.ref.name=ubuntu
LABEL org.opencontainers.image.version=22.04
# 避免APT等工具在构建过程中请求交互式输入
ENV DEBIAN_FRONTEND=noninteractive

# 1. 基础环境配置：安装必要的系统依赖


CMD ["/bin/bash"]
