version: '1.0'
name: pipeline-202601242
displayName: pipeline-202601242
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-49d854d5
    displayName: 未命名2
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: ut@python
        name: unit_test_python
        displayName: Python 单元测试2
        pythonVersion: '3.9'
        commands:
          - '# Python单元测试默认命令'
          - python -m pip install -r require.txt
          - python -m tool.pytest all
        report:
          path: report
          index: index.html
        checkpoints: []
        caches: []
        notify: []
        strategy:
          retry: '0'
