python -m pip install xmltodict>=0.11.0
python -m pip install botocore>=1.12.13
python -m pip install deepdiff>=5.5.0
python -m pip install pproxy>=2.7.0
python -m pip install Quart==0.17
python -m pip install localstack-client>=1.31
python -m pip install Werkzeug==2.1.2
python -m pip install opensearch-py==1.1.0
python -m pip install cbor2>=5.2.0
python -m pip install flask_swagger==0.2.12
python -m pip install pyyaml>=5.1
python -m pip install coverage[toml]>=5.5
python -m pip install moto-ext[all]==3.1.14
python -m pip install pytest==6.2.4
python -m pip install aws-sam-translator>=1.15.1
python -m pip install jsonpath-rw>=1.4.0
python -m pip install stevedore>=3.4.0
python -m pip install rich>=12.3.0
python -m pip install docker==5.0.0
python -m pip install flask-cors>=3.0.3
python -m pip install cachetools~=5.0.0
python -m pip install localstack-ext>=1.0.5.dev
python -m pip install pytest-httpserver>=1.0.1
python -m pip install cryptography
python -m pip install python-dotenv>=0.19.1
python -m pip install typing-extensions
python -m pip install apispec>=5.1.1
python -m pip install boto>=2.49.0
python -m pip install requests>=2.20.0
python -m pip install jsonpath-ng>=1.5.3
python -m pip install requests-aws4auth==0.9
python -m pip install click>=7.0
python -m pip install pytest-json-report
python -m pip install localstack-ext[runtime]>=1.0.5.dev
python -m pip install flask==2.1.3
python -m pip install readerwriterlock>=1.0.7
python -m pip install pyopenssl>=21.0.0
python -m pip install semver>=2.10
python -m pip install jsonpatch>=1.24
python -m pip install pytest-rerunfailures==10.0
python -m pip install psutil>=5.4.8
python -m pip install boto3>=1.20
python -m pip install awscli>=1.22.90
python -m pip install airspeed==0.5.19
python -m pip install tailer>=0.4.1
python -m pip install crontab>=0.22.6
python -m pip install plux>=1.3.1