python -m pip install jsonpatch
python -m pip install localstack-ext[runtime]
python -m pip install flask-cors
python -m pip install localstack-client
python -m pip install aws-sam-translator
python -m pip install pytest-rerunfailures
python -m pip install docker
python -m pip install boto
python -m pip install jsonpath-rw
python -m pip install pyopenssl
python -m pip install apispec
python -m pip install xmltodict
python -m pip install pytest
python -m pip install botocore
python -m pip install cryptography
python -m pip install coverage[toml]
python -m pip install plux
python -m pip install click
python -m pip install jsonpath-ng
python -m pip install boto3
python -m pip install semver
python -m pip install pytest-httpserver
python -m pip install tailer
python -m pip install amazon_kclpy
python -m pip install airspeed
python -m pip install awscli
python -m pip install requests
python -m pip install pyyaml
python -m pip install moto-ext[all]
python -m pip install typing-extensions; python_version < '3.8'
python -m pip install rich
python -m pip install cbor2
python -m pip install opensearch-py
python -m pip install readerwriterlock
python -m pip install pytest-json-report
python -m pip install flask_swagger
python -m pip install pproxy
python -m pip install stevedore
python -m pip install localstack-ext
python -m pip install deepdiff
python -m pip install Quart
python -m pip install crontab
python -m pip install requests-aws4auth
python -m pip install flask
python -m pip install pytest_httpserver
python -m pip install cachetools~=5.0.0
python -m pip install Werkzeug
python -m pip install python-dotenv
python -m pip install psutil